### Site metadata

title: VoxTour.ai Support
description: VoxTour.ai Support Pages

### Build settings

url: https://voxtour.ai
baseurl: https://support.voxtour.ai

theme: just-the-docs

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - LICENSE
  - Makefile
  - README.md
  - planning
  - tour

search_enabled: true

color_scheme: voxtourai
logo: "/assets/images/logo.png"

aux_links:
  "Home":
    - "//support.voxtour.ai"
