### Site metadata

title: VoxTour Support
description: VoxTour.ai Support Pages

### Build settings

url: https://support.voxtour.ai
baseurl: ""

theme: just-the-docs

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - LICENSE
  - Makefile
  - README.md
  - planning
  - tour

search_enabled: true

color_scheme: voxtourai

logo: "/assets/images/logo.png"

aux_links:
  "Voxtour.ai":
    - "//voxtour.ai"
