### Site metadata

title: VoxTour.ai Support
description: VoxTour.ai Support

### Build settings

url: https://voxtourai-support.github.io
baseurl:

theme: just-the-docs

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - LICENSE
  - Makefile
  - README.md

search_enabled: false
