### Site metadata

title: VoxTour Support
description: VoxTour.ai Support Pages

### Build settings

url: https://support.voxtour.ai
baseurl: ""

theme: just-the-docs

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - LICENSE
  - Makefile
  - README.md
  - planning
  - tour

search_enabled: true

color_scheme: voxtourai

logo: "/assets/images/logo.png"

aux_links:
  "Voxtour.ai":
    - "//voxtour.ai"

collections:
  general_information:
    output: true
    permalink: /help-center/general-information/:title/
  features_overview:
    output: true
    permalink: /help-center/features-overview/:title/
  account_management:
    output: true
    permalink: /help-center/account-management/:title/
  settings:
    output: true
    permalink: /help-center/settings/:title/
  tour_usage:
    output: true
    permalink: /help-center/tour-usage/:title/
  troubleshooting:
    output: true
    permalink: /help-center/troubleshooting/:title/